export const queryResponse = [
  {
    state: "Andhra Pradesh",
    district: "Vizianagaram",
    block_strategy: "No",
    activity: "TAS2",
    year: "2022",
    site_name: "Boudh",
  },
  {
    state: "Arunachal Pradesh",
    district: "Anjaw",
    block_strategy: "No",
    activity: "TAS2",
    year: "2022",
    site_name: "Jagatsinghpur",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: null,
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Bantala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Kosala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Madhapur",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Angul",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Banarpal ",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Bantala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "KishoreNagar",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Kosala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Madhapur",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Pallahara",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Talcher",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Bantala Bazar",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Bantool",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Gotamara",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Hulursingha",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Kaniha",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Kosala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Madhapur",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Sankhamar",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Bantala",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Gotamara(FTS)",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Haridanali",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Dhansarpatna",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Ganipur",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Kendupali",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Nijigarh",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Ward No-11",
  },
  {
    state: "Odisha",
    district: "Cuttack",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Ward No.26",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "ASURKHOL",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "BAIDHARNAGAR",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "KAKHARULMAL",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "MANOHARPUR",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "NILABERNI SAHI",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "RAJAMUNDA",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "REAMAL",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2015",
    site_name: "SODA",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Asurkhol",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Chedimara",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Jalisuan",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Ludhar",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Manoharpur",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Nilaberni Sahi",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Rajamunda",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Reamal",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "TAS1",
    year: "2019",
    site_name: "Deoghar",
  },
  {
    state: "Odisha",
    district: "Deogarh",
    block_strategy: "No",
    activity: "TAS2",
    year: "2022",
    site_name: "Deoghar",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Anlabereni",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Beltikiri",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Birasal",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Khajuriakata",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Mathakargola",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Odapada",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Parjang",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2017",
    site_name: "Sriram Chandrapur",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Barihapur",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Barsinga",
  },
  {
    state: "Odisha",
    district: "Dhenkanal",
    block_strategy: "No",
    activity: "DA",
    year: "2018",
    site_name: "Dudhukateni",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Hulursingha(FTS)",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Kosala(FTS)",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Patharmunda",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Patharmunda [ FTS]",
  },
  {
    state: "Odisha",
    district: "Angul",
    block_strategy: "No",
    activity: "IDA",
    year: "2021",
    site_name: "Santhapada",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Bari",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Gobardhanpur",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Godhibasa Mansingbazar Dewanapatna",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Krushna Nagar",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Niaghati",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Nuagaon",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Purana Baleswar",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Ria",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Ada (Simulia)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Baliapati(Basta)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Kharasahapur(Gopal  pur)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Mahatipur (Khaira)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Nuagaon(Baliapal)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Rapeya(Khaira)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "W. No.13(Bls Mun)",
  },
  {
    state: "Odisha",
    district: "Balasore",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Ward No28(Bls Mun)",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Bargarh Ward No.1",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Bargarh Ward No.17",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Birmal",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Dunguri",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Jagalpat",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Jamla",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Panimora",
  },
  {
    state: "Odisha",
    district: "Bargarh",
    block_strategy: "No",
    activity: "DA",
    year: "2021",
    site_name: "Urduna",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Aradi",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Badaostia",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Bankasahi ( Ward no. 12)",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Chudamani",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Hatuari",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Kolha",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Padhuan & Betada",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2019",
    site_name: "Wagalpur, Charampa",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Aradi",
  },
  {
    state: "Odisha",
    district: "Bhadrak",
    block_strategy: "No",
    activity: "DA",
    year: "2020",
    site_name: "Bada Napanga",
  },
];
